### ISSUE TITLE
Version number for accelerate package used here is outdated. Might need to add correct version to requirements.txt

### ISSUE THREAD

**Issue by slokeshrestha26** [teticio/audio-diffusion#48]
I tried running the following command to train on the local machine:

```
accelerate launch --config_file config/accelerate_local.yaml \
scripts/train_unet.py \
--dataset_name data/audio-diffusion-64 \
--hop_length 1024 \
--output_dir models/ddpm-ema-audio-64 \
--train_batch_size 16 \
--num_epochs 100 \
--gradient_accumulation_steps 1 \
--learning_rate 1e-4 \
--lr_warmup_steps 500 \
--mixed_precision no

```

I got the following TypeError: 

```
TypeError: __init__() got an unexpected keyword argument 'logging_dir'
Traceback (most recent call last):
  File "/home/sloke/py_envs/generatingIMU/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/sloke/py_envs/generatingIMU/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 46, in main
    args.func(args)
  File "/home/sloke/py_envs/generatingIMU/lib/python3.8/site-packages/accelerate/commands/launch.py", line 1082, in launch_command
    simple_launcher(args)
  File "/home/sloke/py_envs/generatingIMU/lib/python3.8/site-packages/accelerate/commands/launch.py", line 688, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/sloke/py_envs/generatingIMU/bin/python3', 'scripts/train_unet.py', '--dataset_name', 'data/audio-diffusion-64', '--hop_length', '1024', '--output_dir', 'models/ddpm-ema-audio-64', '--train_batch_size', '16', '--num_epochs', '100', '--gradient_accumulation_steps', '1', '--learning_rate', '1e-4', '--lr_warmup_steps', '500', '--mixed_precision', 'no']' returned non-zero exit status 1.
```

I went ahead and installed accelerate==0.19.0 and error was avoided. 

Proposing to change accelerate to accelerate==0.19.0 in requirements.txt

**Comment by teticio** [comment]
Thanks! Have made the change.
